classDiagram
    namespace Pure_Domain_Entities {
        class Asteroid
        class AsteroidIdentity
        class Orbit
        class PhysicalProperties
        class CloseApproach
        class CloseApproachHistory
        class CloseApproachSummary
        class SentryRiskSignal
    }
    namespace Analytical_Result_Objects {
        class RiskScore
        class RiskExplanation
        class MonteCarloResult
        class SimulationScenario
        class OrbitalGraph
        class OrbitalGraphNode
        class OrbitalSimilarityEdge
        class GNNExperimentResult
    }
    namespace Process_System_Classes {
        class AsteroidFactory
        class GoldFeatureRepository
        class RiskScoreRepository
        class SimulationResultRepository
        class RiskScorer
        class MonteCarloEngine
        class OrbitalMonteCarloEngine
        class OrbitalGraphBuilder
        class GNNExperimentRunner
        class ModelEvidenceBuilder
        class FindingsBuilder
        class IngestionPipeline
        class ETLPipeline
        class GoldBuilder
        class SBDBObjectClient
        class SBDBQueryClient
        class CloseApproachClient
        class SentryClient
        class FastAPIApp
    }

    Asteroid *-- AsteroidIdentity
    Asteroid *-- Orbit
    Asteroid *-- PhysicalProperties
    Asteroid o-- CloseApproachHistory
    CloseApproachHistory *-- CloseApproach
    CloseApproachHistory --> CloseApproachSummary : summarizes
    Asteroid o-- CloseApproachSummary
    Asteroid o-- SentryRiskSignal

    AsteroidFactory --> Asteroid : builds aggregate
    GoldFeatureRepository --> AsteroidFactory
    RiskScoreRepository --> RiskScore
    SimulationResultRepository --> MonteCarloResult

    RiskScorer --> RiskScore : produces
    RiskScorer --> RiskExplanation : explains
    RiskScorer --> Asteroid : interprets features
    MonteCarloEngine --> RiskScorer : rescores perturbations
    MonteCarloEngine --> MonteCarloResult
    OrbitalMonteCarloEngine --> SimulationScenario
    OrbitalMonteCarloEngine --> Orbit
    OrbitalGraphBuilder --> OrbitalGraph
    OrbitalGraph *-- OrbitalGraphNode
    OrbitalGraph *-- OrbitalSimilarityEdge
    GNNExperimentRunner --> OrbitalGraphBuilder
    GNNExperimentRunner --> GNNExperimentResult
    ModelEvidenceBuilder --> RiskScore
    FindingsBuilder --> ModelEvidenceBuilder

    IngestionPipeline --> SBDBObjectClient
    IngestionPipeline --> SBDBQueryClient
    IngestionPipeline --> CloseApproachClient
    IngestionPipeline --> SentryClient
    ETLPipeline --> GoldBuilder
    GoldBuilder --> AsteroidFactory
    FastAPIApp --> GoldFeatureRepository
    FastAPIApp --> RiskScoreRepository
    FastAPIApp --> SimulationResultRepository
